import { FormEvent, useEffect, useMemo, useState, type ReactNode } from "react";
import { api, type Detection, type Display, type Health } from "./api";

type Page = "dashboard" | "setup" | "settings";
type Step = "location" | "source" | "tv" | "artwork" | "display";
const steps: Array<{ id: Step; icon: string; label: string }> = [
  { id: "location", icon: "◎", label: "Location" }, { id: "source", icon: "♬", label: "Detection" },
  { id: "tv", icon: "▣", label: "Frame TV" }, { id: "artwork", icon: "✳", label: "Artwork" }, { id: "display", icon: "◐", label: "Display" },
];
const defaults = { label: "", latitude: "", longitude: "", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, source: "birdweather-public", birdweatherToken: "", birdweatherPublicStationId: "", birdnetUrl: "http://birdnet-go:8080", tvIp: "", tvName: "", displayMode: "collage", collageWindow: "24h", tvAutoUpdate: true, wakeTv: true, quietStart: "22:30", quietEnd: "07:00", refreshMinutes: "5", openrouterApiKey: "", openrouterModel: "", paperTone: "warm cream", palette: "earthy", density: "standard", labels: false, catalogUrl: "" };
type Settings = typeof defaults;

function useRemoteData() {
  const [health, setHealth] = useState<Health>({ status: "starting", version: "", composition_revision: null }); const [display, setDisplay] = useState<Display>({}); const [detections, setDetections] = useState<Detection[]>([]); const [error, setError] = useState("");
  const refresh = async () => { try { const [h, d, events] = await Promise.all([api.health(), api.display(), api.detections()]); setHealth(h); setDisplay(d); setDetections(events); setError(""); } catch { setError("BirdFrame is starting up. Showing local setup controls until the service is ready."); } };
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 30000); return () => window.clearInterval(timer); }, []);
  return { health, display, detections, error, refresh };
}

export function App() {
  const [page, setPage] = useState<Page>("dashboard"); const data = useRemoteData();
  const configured = data.health.status === "ok";
  useEffect(() => { if (!configured && !data.error) setPage("setup"); }, [configured, data.error]);
  return <div className="app-shell"><Sidebar page={page} setPage={setPage} configured={configured} /><main className="main"><Topbar page={page} setPage={setPage} /><div className="content">{data.error && <div className="offline-note"><span>◌</span>{data.error}</div>}{page === "dashboard" && <Dashboard {...data} setPage={setPage} />}{page === "setup" && <Setup onComplete={() => setPage("dashboard")} />}{page === "settings" && <SettingsPanel />}</div></main></div>;
}

function Sidebar({ page, setPage, configured }: { page: Page; setPage: (p: Page) => void; configured: boolean }) { return <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>birdframe</span></div><nav><button className={page === "dashboard" ? "active" : ""} onClick={() => setPage("dashboard")}><i>▦</i>Overview</button><button className={page === "setup" ? "active" : ""} onClick={() => setPage("setup")}><i>◌</i>{configured ? "Setup guide" : "Finish setup"}</button><button className={page === "settings" ? "active" : ""} onClick={() => setPage("settings")}><i>⚙</i>Settings</button></nav><div className="sidebar-bottom"><span className={configured ? "status-dot good" : "status-dot"}></span>{configured ? "Monitoring" : "Not configured"}</div></aside> }
function Topbar({ page, setPage }: { page: Page; setPage: (p: Page) => void }) { return <header className="topbar"><div><p className="eyebrow">{page === "dashboard" ? "YOUR BACKYARD" : "BIRDFRAME"}</p><h1>{page === "dashboard" ? "Good afternoon" : page === "setup" ? "Set up your frame" : "Settings"}</h1></div>{page === "dashboard" && <button className="button soft" onClick={() => setPage("settings")}>⚙ Settings</button>}</header> }

function Dashboard({ health, display, detections, error, refresh, setPage }: ReturnType<typeof useRemoteData> & { setPage: (p: Page) => void }) {
  const [busy, setBusy] = useState(false); const species = display.species || [];
  const trigger = async (kind: "refresh" | "push") => { setBusy(true); try { kind === "refresh" ? await api.refresh() : await api.pushTv(); await refresh(); } finally { setBusy(false); } };
  return <><section className="dashboard-grid"><article className="art-card"><div className="art-card-top"><span className="pill">{display.mode === "latest_visitor" ? "LATEST VISITOR" : "TODAY'S COLLAGE"}</span><span>{display.revision ? `Revision ${display.revision}` : "Awaiting first composition"}</span></div><div className="art-preview">{display.image_url ? <img src={display.image_url} alt="Current BirdFrame artwork" /> : <WaitingArtwork />}</div><div className="art-card-footer"><div><p className="muted">Currently on your display</p><strong>{species.length ? `${species.length} species represented` : "No bird artwork yet"}</strong></div><a href="/api/v1/display/current.jpg" target="_blank">Open image ↗</a></div></article><aside className="dashboard-side"><StatusCard label="BirdFrame service" value={health.status === "ok" ? "Running" : "Starting"} state={health.status === "ok" ? "healthy" : "warning"} detail={`Version ${health.version || "—"}`} /><StatusCard label="Current composition" value={display.revision ? `Revision ${display.revision}` : "Not rendered"} state={display.revision ? "healthy" : "warning"} detail={display.mode === "latest_visitor" ? "Latest visitor mode" : "Collage mode"} /><StatusCard label="Artwork library" value={`${species.length} active species`} state={species.length > 0 ? "healthy" : "warning"} detail={species.length > 0 ? "Ready to display" : "Waiting for detections"} /></aside></section><section className="lower-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Latest detections</h2></div><button className="text-button" onClick={() => setPage("settings")}>Detection settings →</button></div>{detections.length ? <div className="detection-list">{detections.map((d) => <DetectionRow key={d.id} detection={d} />)}</div> : <EmptyState icon="♬" title="Waiting for birds" description={error ? "Connect your source to begin receiving detections." : "New detections will appear here and update the artwork."} />}</article><article className="panel actions"><p className="eyebrow">DISPLAY CONTROL</p><h2>Keep the frame alive</h2><p className="muted">The image endpoint is always available for other screens and apps.</p><button className="button primary" disabled={busy} onClick={() => void trigger("refresh")}>↻ {busy ? "Updating…" : "Refresh composition"}</button><button className="button ghost" disabled={busy} onClick={() => void trigger("push")}>▣ Send current art to TV</button></article></section></>;
}
function StatusCard({ label, value, detail, state }: { label: string; value: string; detail: string; state: string }) { return <article className="status-card"><div className="status-line"><span className={`status-dot ${state === "healthy" ? "good" : "warn"}`}></span><span>{label}</span></div><strong>{value}</strong><p>{detail}</p></article> }
function DetectionRow({ detection }: { detection: Detection }) { const when = useMemo(() => new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(detection.detected_at)), [detection.detected_at]); return <div className="detection"><div className="bird-thumb">♩</div><div><strong>{detection.common_name}</strong><p><em>{detection.scientific_name || "Unidentified species"}</em> · {detection.source_type || "Detection"}</p></div><div className="detection-meta"><strong>{Math.round((detection.confidence || 0) * 100)}%</strong><span>{when}</span></div></div> }
function EmptyState({ icon, title, description }: { icon: string; title: string; description: string }) { return <div className="empty"><div>{icon}</div><strong>{title}</strong><p>{description}</p></div> }
function WaitingArtwork() { return <div className="waiting-art"><span className="sun"></span><span className="bird bird-one">⌁</span><span className="bird bird-two">⌁</span><p>Your first birds will gather here</p></div> }

function Setup({ onComplete }: { onComplete: () => void }) { const [step, setStep] = useState<Step>("location"); const [form, setForm] = useState<Settings>(defaults); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const current = steps.findIndex((s) => s.id === step);
  // The setup guide is also used after first-run. Hydrating it prevents a
  // later visit from presenting defaults that could overwrite saved settings.
  useEffect(() => { void api.settings().then((raw) => setForm(fromApiSettings(raw))).catch(() => undefined); }, []);
  const update = (key: keyof Settings, value: string | boolean) => setForm((old) => ({ ...old, [key]: value }));
  const next = async () => { if (current < steps.length - 1) { setStep(steps[current + 1].id); return; } setSaving(true); try { await api.saveSettings(toPayload(form)); setNotice("Your BirdFrame is ready. It will keep watching for visitors."); } catch { setNotice("Settings are ready to save when the BirdFrame service API is available."); } finally { setSaving(false); } };
  return <div className="setup"><div className="setup-intro"><p className="eyebrow">FIRST-RUN SETUP</p><h2>A quiet window onto your backyard.</h2><p>BirdFrame keeps bird detection local where possible, then turns your visitors into a living artwork.</p></div><div className="stepper">{steps.map((item, i) => <button key={item.id} className={item.id === step ? "current" : i < current ? "complete" : ""} onClick={() => setStep(item.id)}><span>{i < current ? "✓" : item.icon}</span>{item.label}</button>)}</div><article className="setup-panel"><div className="step-title"><span>0{current + 1}</span><div><p className="eyebrow">{steps[current].label}</p><h2>{stepTitle(step, form.source)}</h2></div></div>{step === "location" && <LocationForm form={form} update={update} />}{step === "source" && <SourceForm form={form} update={update} />}{step === "tv" && <TvForm form={form} update={update} />}{step === "artwork" && <ArtworkForm form={form} update={update} />}{step === "display" && <DisplayForm form={form} update={update} />}<div className="setup-actions"><button className="button ghost" disabled={current === 0} onClick={() => setStep(steps[current - 1].id)}>← Back</button><div>{notice && <span className="form-notice">{notice}</span>}<button className="button primary" disabled={saving} onClick={() => void next()}>{current === steps.length - 1 ? saving ? "Saving…" : "Finish setup" : "Continue →"}</button></div></div>{notice && current === steps.length - 1 && <button className="text-button finish" onClick={onComplete}>Go to dashboard →</button>}</article></div> }
function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label> }
function LocationForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <div className="form-grid"><Field label="Place name"><input value={form.label} placeholder="e.g. Oslo, Norway" onChange={(e) => update("label", e.target.value)} /></Field><Field label="Time zone"><input value={form.timezone} onChange={(e) => update("timezone", e.target.value)} /></Field><Field label="Latitude" hint="Stored locally; used to filter likely species."><input value={form.latitude} inputMode="decimal" placeholder="59.9139" onChange={(e) => update("latitude", e.target.value)} /></Field><Field label="Longitude"><input value={form.longitude} inputMode="decimal" placeholder="10.7522" onChange={(e) => update("longitude", e.target.value)} /></Field><div className="privacy-note">⌂ <span><strong>Your location stays with BirdFrame.</strong> It is only shared with an occurrence provider if you choose one for regional artwork.</span></div></div> }
function SourceForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <><div className="choice-row"><button className={form.source === "birdweather-public" ? "choice selected" : "choice"} onClick={() => update("source", "birdweather-public")}><span>☁</span><strong>Public BirdWeather</strong><p>Read a public station by ID. No token or second container needed.</p></button><button className={form.source === "birdweather" ? "choice selected" : "choice"} onClick={() => update("source", "birdweather")}><span>⌁</span><strong>My BirdWeather station</strong><p>Use a private station token you own.</p></button><button className={form.source === "birdnet" ? "choice selected" : "choice"} onClick={() => update("source", "birdnet")}><span>♬</span><strong>Local microphone</strong><p>Connect through the optional BirdNET-Go sidecar.</p></button></div>{form.source === "birdweather-public" ? <Field label="Public station ID" hint="For PUC-2505-Oslo Norway, enter 2505. No token is stored."><input type="number" min="1" inputMode="numeric" value={form.birdweatherPublicStationId} placeholder="2505" onChange={(e) => update("birdweatherPublicStationId", e.target.value)} /></Field> : form.source === "birdweather" ? <Field label="Station token" hint="Saved encrypted; never shown again after saving."><input type="password" value={form.birdweatherToken} placeholder="Paste your BirdWeather station token" onChange={(e) => update("birdweatherToken", e.target.value)} /></Field> : <Field label="BirdNET-Go address" hint="Start Compose with the local-audio profile first."><input value={form.birdnetUrl} onChange={(e) => update("birdnetUrl", e.target.value)} /></Field>}<p className="help-text">BirdFrame verifies the active source when it starts monitoring. You can revisit this setting at any time.</p></> }
function TvForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <><div className="tv-illustration">▣<span>Samsung<br />The Frame</span></div><div className="form-grid"><Field label="TV name"><input value={form.tvName} placeholder="Living room Frame" onChange={(e) => update("tvName", e.target.value)} /></Field><Field label="IP address"><input value={form.tvIp} placeholder="192.168.1.42" onChange={(e) => update("tvIp", e.target.value)} /></Field></div><p className="help-text">Save this address to pair the TV. Then use “Send current art to TV” from the dashboard and approve the request on the TV.</p></> }
function ArtworkForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <><div className="art-style-preview"><div className="print-bird">♧</div><div><p className="eyebrow">DEFAULT PRESET</p><h3>Kachō-e visitors</h3><p>Warm paper, spare watercolor, and precise ink linework inspired by Japanese bird-and-flower prints.</p></div></div><div className="form-grid three"><Field label="Paper tone"><select value={form.paperTone} onChange={(e) => update("paperTone", e.target.value)}><option>warm cream</option><option>aged mulberry</option><option>soft white</option></select></Field><Field label="Palette"><select value={form.palette} onChange={(e) => update("palette", e.target.value)}><option>earthy</option><option>muted garden</option><option>indigo & vermillion</option></select></Field><Field label="Collage density"><select value={form.density} onChange={(e) => update("density", e.target.value)}><option>standard</option><option>sparse</option><option>full</option></select></Field></div><div className="toggle-row"><div><strong>Numbered Norwegian & Latin legend</strong><p>Number each bird and list its Norwegian and scientific name in a script legend on the right.</p></div><button className={form.labels ? "toggle on" : "toggle"} aria-label="Toggle numbered Norwegian and Latin legend" onClick={() => update("labels", !form.labels)}><i></i></button></div><div className="form-grid"><Field label="OpenRouter API key" hint="Optional now; encrypted at rest when you finish setup."><input type="password" value={form.openrouterApiKey} placeholder="sk-or-v1-…" onChange={(e) => update("openrouterApiKey", e.target.value)} /></Field><Field label="Preferred image model" hint="You can load the current model list and generate artwork in Settings."><input value={form.openrouterModel} placeholder="e.g. provider/model" onChange={(e) => update("openrouterModel", e.target.value)} /></Field></div><div className="callout"><span>✳</span><div><strong>Generate your library after setup</strong><p>Settings includes model loading, one-click generation from observed species, job status, and an activity log.</p></div></div></> }
function DisplayForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <><div className="choice-row"><button className={form.displayMode === "collage" ? "choice selected" : "choice"} onClick={() => update("displayMode", "collage")}><span>✣</span><strong>Living collage</strong><p>Unique visitors gather into one daily artwork.</p></button><button className={form.displayMode === "latest" ? "choice selected" : "choice"} onClick={() => update("displayMode", "latest")}><span>◉</span><strong>Latest visitor</strong><p>One bird, large and serene, for each new sighting.</p></button></div><div className="form-grid three"><Field label="Collage window"><select value={form.collageWindow} onChange={(e) => update("collageWindow", e.target.value)}><option value="1h">1 hour</option><option value="12h">12 hours</option><option value="24h">24 hours</option><option value="7d">7 days</option></select></Field><Field label="Refresh at most every"><select value={form.refreshMinutes} onChange={(e) => update("refreshMinutes", e.target.value)}><option value="5">5 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option></select></Field><Field label="TV updates"><select><option>Art Mode</option><option>Art Mode + Wake</option></select></Field></div><div className="toggle-row"><div><strong>Automatically select new artwork on TV</strong><p>Uploads and selects the newest composition in Art Mode at the chosen cadence.</p></div><button className={form.tvAutoUpdate ? "toggle on" : "toggle"} aria-label="Toggle automatic TV updates" onClick={() => update("tvAutoUpdate", !form.tvAutoUpdate)}><i></i></button></div><div className="toggle-row"><div><strong>Wake TV for a new composition</strong><p>Only outside your quiet hours.</p></div><button className={form.wakeTv ? "toggle on" : "toggle"} aria-label="Toggle wake TV" onClick={() => update("wakeTv", !form.wakeTv)}><i></i></button></div><div className="form-grid"><Field label="Quiet hours start"><input type="time" value={form.quietStart} onChange={(e) => update("quietStart", e.target.value)} /></Field><Field label="Quiet hours end"><input type="time" value={form.quietEnd} onChange={(e) => update("quietEnd", e.target.value)} /></Field></div><div className="privacy-note">▧ <span><strong>A stable image URL is ready for your other screens.</strong> BirdFrame serves the exact same 16:9 JPEG it sends to the TV at <code>/api/v1/display/current.jpg</code>.</span></div></> }
function stepTitle(step: Step, source: string) { return ({ location: "Where do your birds live?", source: source === "birdweather-public" ? "Connect a public BirdWeather station" : source === "birdweather" ? "Connect your BirdWeather station" : "Listen with a local microphone", tv: "Find your Samsung Frame", artwork: "Choose the character of your artwork", display: "Set the rhythm of your display" })[step]; }
function toPayload(s: Settings) { return { location_label: s.label, latitude: s.latitude ? Number(s.latitude) : null, longitude: s.longitude ? Number(s.longitude) : null, timezone: s.timezone, detection_source: s.source === "birdnet" ? "birdnet_go" : s.source === "birdweather-public" ? "birdweather_public" : "birdweather", birdweather_token: s.birdweatherToken || undefined, birdweather_public_station_id: s.birdweatherPublicStationId ? Number(s.birdweatherPublicStationId) : null, birdnet_go_url: s.birdnetUrl, tv_host: s.tvIp, display_mode: s.displayMode === "latest" ? "latest_visitor" : "collage", collage_hours: s.collageWindow === "7d" ? 168 : Number.parseInt(s.collageWindow, 10), tv_auto_update_enabled: s.tvAutoUpdate, tv_wake_enabled: s.wakeTv, tv_quiet_hours_start: s.quietStart, tv_quiet_hours_end: s.quietEnd, tv_update_minutes: Number(s.refreshMinutes), openrouter_api_key: s.openrouterApiKey || undefined, openrouter_model: s.openrouterModel, paper_tone: s.paperTone === "warm cream" ? "#f2e4c9" : s.paperTone === "aged mulberry" ? "#ddc89e" : "#fffaf0", palette: s.palette === "earthy" ? "classic" : s.palette === "muted garden" ? "muted" : "vivid", collage_density: s.density, labels_enabled: s.labels, package_catalog_url: s.catalogUrl }; }
function fromApiSettings(raw: Record<string, unknown>): Settings { return { ...defaults, label: String(raw.location_label || ""), latitude: raw.latitude == null ? "" : String(raw.latitude), longitude: raw.longitude == null ? "" : String(raw.longitude), timezone: String(raw.timezone || defaults.timezone), source: raw.detection_source === "birdnet_go" ? "birdnet" : raw.detection_source === "birdweather_public" ? "birdweather-public" : "birdweather", birdweatherPublicStationId: raw.birdweather_public_station_id == null ? "" : String(raw.birdweather_public_station_id), birdnetUrl: String(raw.birdnet_go_url || defaults.birdnetUrl), tvIp: String(raw.tv_host || ""), displayMode: raw.display_mode === "latest_visitor" ? "latest" : "collage", collageWindow: `${raw.collage_hours || 24}h`.replace("168h", "7d"), tvAutoUpdate: raw.tv_auto_update_enabled !== false, wakeTv: Boolean(raw.tv_wake_enabled), quietStart: String(raw.tv_quiet_hours_start || ""), quietEnd: String(raw.tv_quiet_hours_end || ""), refreshMinutes: String(raw.tv_update_minutes || 5), openrouterModel: String(raw.openrouter_model || ""), paperTone: raw.paper_tone === "#ddc89e" ? "aged mulberry" : raw.paper_tone === "#fffaf0" ? "soft white" : "warm cream", palette: raw.palette === "muted" ? "muted garden" : raw.palette === "vivid" ? "indigo & vermillion" : "earthy", density: String(raw.collage_density || "standard"), labels: Boolean(raw.labels_enabled), catalogUrl: String(raw.package_catalog_url || "") }; }

function SettingsPanel() {
  const [form, setForm] = useState<Settings>(defaults); const [message, setMessage] = useState("");
  const [models, setModels] = useState<Array<{ id: string; name?: string }>>([]); const [operations, setOperations] = useState("");
  const update = (key: keyof Settings, value: string | boolean) => setForm((old) => ({ ...old, [key]: value }));
  useEffect(() => { void api.settings().then((raw) => setForm(fromApiSettings(raw))).catch(() => undefined); }, []);
  const save = async (e?: FormEvent) => { e?.preventDefault(); try { await api.saveSettings(toPayload(form)); setMessage("Settings saved. API keys are encrypted at rest."); return true; } catch { setMessage("Could not save yet. Make sure the BirdFrame API is running."); return false; } };
  const loadModels = async () => { if (!await save()) return; try { setModels(await api.models()); setOperations("Image-capable OpenRouter models loaded."); } catch { setOperations("Could not load models. Check the API key and try again."); } };
  const generate = async () => { if (!await save()) return; try { const species = (await api.occurrences()).slice(0, 12).map(({ common_name, scientific_name }) => ({ common_name, scientific_name })); if (!species.length) { setOperations("No detected species are available yet."); return; } const job = await api.generateArt({ species, poses: "both" }); setOperations(`Artwork job ${job.id} queued for ${species.length} species. Track it in Activity log below.`); } catch { setOperations("Could not start artwork generation. Load a model and confirm detections are available."); } };
  return <form className="settings-form" onSubmit={save}>
    <section className="settings-section"><div><p className="eyebrow">GENERAL</p><h2>Home territory</h2><p>Controls regional filtering and the seasonal artwork list.</p></div><div className="form-grid"><Field label="Place name"><input value={form.label} onChange={(e) => update("label", e.target.value)} placeholder="Oslo, Norway" /></Field><Field label="Time zone"><input value={form.timezone} onChange={(e) => update("timezone", e.target.value)} /></Field><Field label="Latitude"><input value={form.latitude} onChange={(e) => update("latitude", e.target.value)} /></Field><Field label="Longitude"><input value={form.longitude} onChange={(e) => update("longitude", e.target.value)} /></Field></div></section>
    <section className="settings-section"><div><p className="eyebrow">DETECTION</p><h2>One active source</h2><p>Switching sources preserves your history but never merges live streams.</p></div><div><div className="segmented"><button type="button" className={form.source === "birdweather-public" ? "selected" : ""} onClick={() => update("source", "birdweather-public")}>Public BirdWeather</button><button type="button" className={form.source === "birdweather" ? "selected" : ""} onClick={() => update("source", "birdweather")}>My BirdWeather</button><button type="button" className={form.source === "birdnet" ? "selected" : ""} onClick={() => update("source", "birdnet")}>Local microphone</button></div>{form.source === "birdweather-public" ? <Field label="Public station ID" hint="Use 2505 for PUC-2505-Oslo Norway. No token required."><input type="number" min="1" value={form.birdweatherPublicStationId} placeholder="2505" onChange={(e) => update("birdweatherPublicStationId", e.target.value)} /></Field> : form.source === "birdweather" ? <Field label="BirdWeather station token" hint="Configured secrets are never returned by BirdFrame."><input type="password" placeholder="••••••••••••" value={form.birdweatherToken} onChange={(e) => update("birdweatherToken", e.target.value)} /></Field> : <Field label="BirdNET-Go URL"><input value={form.birdnetUrl} onChange={(e) => update("birdnetUrl", e.target.value)} /></Field>}</div></section>
    <section className="settings-section"><div><p className="eyebrow">OPENROUTER ARTWORK</p><h2>Create your bird library</h2><p>Save your key, load the available image models, choose one, then generate reusable bird assets from the species BirdFrame has observed.</p></div><div className="form-grid"><Field label="OpenRouter API key" hint="Encrypted at rest and never returned to the browser after saving."><input type="password" value={form.openrouterApiKey} placeholder="sk-or-v1-…" onChange={(e) => update("openrouterApiKey", e.target.value)} /></Field><Field label="Image model"><input list="openrouter-models" value={form.openrouterModel} placeholder="Save key, then load models" onChange={(e) => update("openrouterModel", e.target.value)} /><datalist id="openrouter-models">{models.map((model) => <option key={model.id} value={model.id}>{model.name || model.id}</option>)}</datalist></Field><Field label="Package catalog URL"><input value={form.catalogUrl} placeholder="https://github.com/.../catalog.json" onChange={(e) => update("catalogUrl", e.target.value)} /></Field><Field label="Paper tone"><select value={form.paperTone} onChange={(e) => update("paperTone", e.target.value)}><option>warm cream</option><option>aged mulberry</option><option>soft white</option></select></Field><Field label="Palette"><select value={form.palette} onChange={(e) => update("palette", e.target.value)}><option>earthy</option><option>muted garden</option><option>indigo & vermillion</option></select></Field></div><div className="setup-actions"><button type="button" className="button ghost" onClick={() => void loadModels()}>Load image models</button><button type="button" className="button primary" onClick={() => void generate()}>Generate artwork for 12 observed species</button></div>{operations && <p className="form-notice">{operations}</p>}<p className="help-text">Generated PNG assets and compositions are stored under <code>/data/art</code>; Docker Compose maps that directory to <code>./data</code> by default, so they survive image/container updates.</p></section>
    <section className="settings-section"><div><p className="eyebrow">COLLAGE LEGEND</p><h2>Bird names</h2><p>Add a numbered key to the right of the collage, with each bird's Norwegian and scientific name.</p></div><div><div className="toggle-row"><div><strong>Show Norwegian &amp; Latin bird names</strong><p>Birds are numbered in the artwork and matched to a handwritten-style legend. Turn it off for artwork without text.</p></div><button type="button" className={form.labels ? "toggle on" : "toggle"} aria-label="Toggle Norwegian and Latin bird names" onClick={() => update("labels", !form.labels)}><i></i></button></div><Field label="Collage coverage" hint="Full uses more of the 16:9 screen; sparse leaves more breathing room."><select value={form.density} onChange={(e) => update("density", e.target.value)}><option value="sparse">Sparse</option><option value="standard">Balanced</option><option value="full">Full screen</option></select></Field></div></section>
    <ActivityLog />
    <section className="settings-section"><div><p className="eyebrow">DISPLAY API</p><h2>Same art, anywhere</h2><p>The JPEG endpoint serves the byte-identical composition sent to the Frame.</p></div><div className="api-url"><code>{window.location.origin}/api/v1/display/current.jpg</code><a href="/api/v1/display/current.jpg" target="_blank">Open ↗</a></div></section>
    <footer className="save-bar"><span>{message}</span><button className="button primary" type="submit">Save changes</button></footer>
  </form>;
}

function ActivityLog() { const [entries, setEntries] = useState<Array<{ id: number; level: string; message: string; created_at: string }>>([]); const refresh = () => void api.logs().then(setEntries).catch(() => undefined); useEffect(() => { refresh(); const timer = window.setInterval(refresh, 15000); return () => window.clearInterval(timer); }, []); return <section className="settings-section"><div><p className="eyebrow">ACTIVITY LOG</p><h2>What BirdFrame is doing</h2><p>Recent source, generation, and settings events. Credentials are never written here.</p></div><div><button type="button" className="button ghost" onClick={refresh}>Refresh log</button><div className="detection-list">{entries.length ? entries.map((entry) => <div className="detection" key={entry.id}><div className="bird-thumb">{entry.level === "ERROR" ? "!" : entry.level === "WARNING" ? "!" : "i"}</div><div><strong>{entry.level}</strong><p>{entry.message}</p></div><div className="detection-meta"><span>{new Date(entry.created_at).toLocaleTimeString()}</span></div></div>) : <EmptyState icon="i" title="No events yet" description="Events will appear after saving settings or receiving detections." />}</div></div></section> }
