import { FormEvent, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { api, ApiError, getApiKey, setApiKey, type ApiKey, type ApiKeyCreated, type AuthSession, type Display, type Health, type LogEntry, type RecentBird, type User } from "./api";

type Page = "dashboard" | "birds" | "logs" | "setup" | "settings" | "account";
type Step = "location" | "source" | "tv" | "artwork" | "assets" | "display";
const steps: Array<{ id: Step; icon: string; label: string }> = [
  { id: "location", icon: "◎", label: "Location" }, { id: "source", icon: "♬", label: "Detection" },
  { id: "tv", icon: "▣", label: "Frame TV" },
  { id: "artwork", icon: "✳", label: "Artwork" }, { id: "assets", icon: "▤", label: "Assets" },
  { id: "display", icon: "◈", label: "Display & TV" },
];
const defaults = { label: "", latitude: "", longitude: "", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, language: "no", source: "birdweather-public", birdweatherToken: "", birdweatherPublicStationId: "", birdnetUrl: "http://birdnet-go:8080", tvIp: "", tvName: "", tvMac: "", displayMode: "collage", collageWindow: "24h", tvAutoUpdate: true, wakeTv: false, quietStart: "", quietEnd: "", refreshMinutes: "5", openrouterApiKey: "", openrouterModel: "", paperTone: "warm cream", palette: "earthy", density: "standard", collageStyle: "classic", labels: false, scriptSize: "medium", catalogUrl: "", assetPack: "all", assetVariant: "illustrations" };
type Settings = typeof defaults;

function useRemoteData() {
  const [health, setHealth] = useState<Health>({ status: "starting", version: "", composition_revision: null }); const [display, setDisplay] = useState<Display>({}); const [birds, setBirds] = useState<RecentBird[]>([]); const [error, setError] = useState("");
  const refresh = async () => { try { setHealth(await api.health()); const [d, recentBirds] = await Promise.all([api.display(), api.birds()]); setDisplay(d); setBirds(recentBirds); setError(""); } catch (err) { if (err instanceof ApiError && err.status === 401) { setApiKey(""); setError(""); } else { setError("BirdFrame is starting up. Showing local setup controls until the service is ready."); } } };
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 30000); return () => window.clearInterval(timer); }, []);
  return { health, display, birds, error, refresh };
}

export function App() {
  const [page, setPage] = useState<Page>("dashboard"); const data = useRemoteData();
  const [session, setSession] = useState<{ username: string; is_admin: boolean } | null>(null);
  const [authChecking, setAuthChecking] = useState(!!getApiKey());
  const previouslyConfigured = useRef(false);
  useEffect(() => {
    if (!getApiKey()) { setAuthChecking(false); return; }
    api.me().then(setSession).catch(() => setApiKey("")).finally(() => setAuthChecking(false));
  }, []);
  const configured = data.health.status === "ok" && !data.health.needs_setup;
  useEffect(() => {
    // Health starts as "starting", so a freshly loaded page briefly looks
    // unconfigured. Only force the setup pane for a genuinely unconfigured
    // installation, and once it reports configured, always land on Overview.
    if (configured && !previouslyConfigured.current) setPage("dashboard");
    if (!configured && !data.error) setPage("setup");
    previouslyConfigured.current = configured;
  }, [configured, data.error]);
  if (authChecking) return <div className="auth-shell"><p className="help-text">Checking session…</p></div>;
  if (!getApiKey()) return <div className="auth-shell">{data.error && <div className="offline-note"><span>◌</span>{data.error}</div>}<AuthScreen needsAdmin={data.health.needs_admin} onAuthed={(s) => { setApiKey(s.api_key); setSession({ username: s.username, is_admin: s.is_admin }); void data.refresh(); }} /></div>;
  const logout = async () => { try { await api.logout(); } catch { /* key already invalid */ } setApiKey(""); setSession(null); };
  return <div className="app-shell"><Sidebar page={page} setPage={setPage} configured={configured} user={session?.username || ""} onLogout={() => void logout()} /><main className="main"><Topbar page={page} setPage={setPage} /><div className="content">{data.error && <div className="offline-note"><span>◌</span>{data.error}</div>}{page === "dashboard" && <Dashboard {...data} setPage={setPage} />}{page === "birds" && <BirdsPage birds={data.birds} />}{page === "logs" && <LogsPage />}{page === "setup" && <Setup configured={configured} onComplete={() => { void data.refresh(); setPage("dashboard"); }} />}{page === "settings" && <SettingsPanel />}{page === "account" && <AccountPage user={session || { username: "", is_admin: false }} />}</div></main></div>;
}

function Sidebar({ page, setPage, configured, user, onLogout }: { page: Page; setPage: (p: Page) => void; configured: boolean; user: string; onLogout: () => void }) { return <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>birdframe</span></div><nav><button className={page === "dashboard" ? "active" : ""} onClick={() => setPage("dashboard")}><i>▦</i>Overview</button><button className={page === "birds" ? "active" : ""} onClick={() => setPage("birds")}><i>♧</i>Birds</button><button className={page === "logs" ? "active" : ""} onClick={() => setPage("logs")}><i>≡</i>Activity log</button><button className={page === "setup" ? "active" : ""} onClick={() => setPage("setup")}><i>◌</i>{configured ? "Setup" : "Finish setup"}</button><button className={page === "settings" ? "active" : ""} onClick={() => setPage("settings")}><i>⚙</i>Settings</button><button className={page === "account" ? "active" : ""} onClick={() => setPage("account")}><i>🔑</i>Account</button></nav><div className="sidebar-bottom"><span className={configured ? "status-dot good" : "status-dot"}></span><span>{configured ? "Monitoring" : "Not configured"}</span><div className="sidebar-user"><span>👤 {user}</span><button type="button" className="text-button" onClick={onLogout}>Log out</button></div></div></aside> }
function Topbar({ page, setPage }: { page: Page; setPage: (p: Page) => void }) { const title = page === "dashboard" ? "Good afternoon" : page === "setup" ? "Set up your frame" : page === "logs" ? "Activity log" : page === "birds" ? "Detected birds" : page === "account" ? "Account & API keys" : "Settings"; return <header className="topbar"><div><p className="eyebrow">{page === "dashboard" ? "YOUR BACKYARD" : "BIRDFRAME"}</p><h1>{title}</h1></div>{page === "dashboard" && <button className="button soft" onClick={() => setPage("settings")}>⚙ Settings</button>}</header> }

function Dashboard({ health, display, birds, error, refresh, setPage }: ReturnType<typeof useRemoteData> & { setPage: (p: Page) => void }) {
  const [busy, setBusy] = useState(false); const [tvJob, setTvJob] = useState<number | null>(null); const [tvNotice, setTvNotice] = useState(""); const species = display.species || [];
  const trigger = async (kind: "refresh" | "push") => { setBusy(true); try { if (kind === "refresh") { await api.refresh(); await refresh(); } else { const job = await api.pushTv(); setTvJob(job.id); setTvNotice("Sending artwork to TV…"); } } catch (err) { if (kind === "push") setTvNotice(err instanceof ApiError ? err.message : "Could not queue TV push."); } finally { setBusy(false); } };
  useEffect(() => { if (tvJob == null) return; let alive = true; const poll = async () => { try { const jobs = await api.jobs(); const job = jobs.find((item) => item.id === tvJob); if (!job || !alive) return; if (job.status === "completed") { setTvNotice("Artwork sent to TV."); setTvJob(null); } else if (job.status === "failed") { setTvNotice(`TV push failed: ${job.error || "unknown error"}`); setTvJob(null); } } catch { /* keep polling */ } }; void poll(); const timer = window.setInterval(() => void poll(), 2000); return () => { alive = false; window.clearInterval(timer); }; }, [tvJob]);
  return <><section className="dashboard-grid"><article className="art-card"><div className="art-card-top"><span className="pill">{display.mode === "latest_visitor" ? "LATEST VISITOR" : display.mode === "journal" ? "TODAY'S JOURNAL" : "TODAY'S COLLAGE"}</span><span>{display.revision ? `Revision ${display.revision}` : "Awaiting first composition"}</span></div><div className="art-preview">{display.image_url ? <img src={display.image_url} alt="Current BirdFrame artwork" /> : <WaitingArtwork />}</div><div className="art-card-footer"><div><p className="muted">Currently on your display</p><strong>{species.length ? `${species.length} species represented` : "No bird artwork yet"}</strong></div><a href="/api/v1/display/current.jpg" target="_blank">Open image ↗</a></div><div className="art-actions"><button className="button primary" disabled={busy} onClick={() => void trigger("refresh")}>↻ {busy ? "Updating…" : "Refresh composition"}</button><button className="button ghost" disabled={busy} onClick={() => void trigger("push")}>▣ Send current art to TV</button></div>{tvNotice && <p className="form-notice">{tvNotice}</p>}</article><aside className="dashboard-side"><StatusCard label="BirdFrame service" value={health.status === "ok" ? "Running" : "Starting"} state={health.status === "ok" ? "healthy" : "warning"} detail={`Version ${health.version || "—"}`} /><StatusCard label="Current composition" value={display.revision ? `Revision ${display.revision}` : "Not rendered"} state={display.revision ? "healthy" : "warning"} detail={display.mode === "latest_visitor" ? "Latest visitor mode" : display.mode === "journal" ? "Journal mode" : "Collage mode"} /><StatusCard label="Artwork library" value={`${species.length} active species`} state={species.length > 0 ? "healthy" : "warning"} detail={species.length > 0 ? "Ready to display" : "Waiting for detections"} /></aside></section><section className="lower-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">LAST 24 HOURS</p><h2>Birds detected</h2></div><button className="text-button" onClick={() => setPage("birds")}>View all birds →</button></div>{birds.length ? <div className="detection-list">{birds.slice(0, 3).map((bird) => <BirdRow key={bird.scientific_name || bird.common_name} bird={bird} compact />)}</div> : <EmptyState icon="♬" title="Waiting for birds" description={error ? "Connect your source to begin receiving detections." : "New detections will appear here and update the artwork."} />}</article></section></>;
}
function StatusCard({ label, value, detail, state }: { label: string; value: string; detail: string; state: string }) { return <article className="status-card"><div className="status-line"><span className={`status-dot ${state === "healthy" ? "good" : "warn"}`}></span><span>{label}</span></div><strong>{value}</strong><p>{detail}</p></article> }
function BirdRow({ bird, compact = false, action }: { bird: RecentBird; compact?: boolean; action?: ReactNode }) { const when = useMemo(() => new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(bird.latest_at)), [bird.latest_at]); return <div className={`detection bird-row ${compact ? "compact" : ""}`}><img className="bird-thumb bird-image" src={bird.image_url} alt="" /><div><strong>{bird.common_name}</strong><p><em>{bird.scientific_name || "Unidentified species"}</em></p></div><div className="detection-meta"><strong>{bird.count} {bird.count === 1 ? "detection" : "detections"}</strong><span>{when}</span></div>{action}</div> }
function BirdsPage({ birds }: { birds: RecentBird[] }) {
  const [pending, setPending] = useState<Record<string, "busy" | "queued">>({}); const [notice, setNotice] = useState("");
  const generate = async (bird: RecentBird) => { const key = bird.scientific_name || bird.common_name; setPending((current) => ({ ...current, [key]: "busy" })); setNotice(""); try { await api.generateArt({ species: [{ common_name: bird.common_name, scientific_name: bird.scientific_name || "" }], poses: "both" }); setPending((current) => ({ ...current, [key]: "queued" })); } catch (err) { setNotice(`Could not start artwork for ${bird.common_name}: ${err instanceof ApiError ? err.message : "check the OpenRouter setup in Settings."}`); setPending((current) => { const next = { ...current }; delete next[key]; return next; }); } };
  const missing = birds.filter((bird) => !bird.has_artwork).length;
  return <section className="panel birds-page"><div className="panel-heading"><div><p className="eyebrow">LAST 24 HOURS</p><h2>Detected birds</h2><p className="muted">One row per species, with the artwork BirdFrame uses in collages. Species without artwork get a placeholder until you generate or install their image.</p></div><strong>{birds.length} species</strong></div>{birds.length ? <div className="detection-list">{birds.map((bird) => <BirdRow key={bird.scientific_name || bird.common_name} bird={bird} action={bird.has_artwork ? undefined : <button type="button" className="button small ghost" disabled={!!pending[bird.scientific_name || bird.common_name]} onClick={() => void generate(bird)}>{pending[bird.scientific_name || bird.common_name] === "busy" ? "Starting…" : pending[bird.scientific_name || bird.common_name] === "queued" ? "Queued ✓" : "Generate image"}</button>} />)}</div> : <EmptyState icon="♬" title="Waiting for birds" description="Detected species will appear here." />}{missing > 0 && <p className="help-text">{missing} {missing === 1 ? "species is" : "species are"} missing artwork — generate one per bird above, or install an asset pack in Settings.</p>}{notice && <p className="form-notice">{notice}</p>}</section> }
function EmptyState({ icon, title, description }: { icon: string; title: string; description: string }) { return <div className="empty"><div>{icon}</div><strong>{title}</strong><p>{description}</p></div> }
function WaitingArtwork() { return <div className="waiting-art"><span className="sun"></span><span className="bird bird-one">⌁</span><span className="bird bird-two">⌁</span><p>Your first birds will gather here</p></div> }

function AuthScreen({ needsAdmin, onAuthed }: { needsAdmin?: boolean; onAuthed: (s: AuthSession) => void }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(""); if (username.trim().length < 3) { setError("Username must be at least 3 characters."); return; } if (password.length < 8) { setError("Password must be at least 8 characters."); return; } setBusy(true); try { onAuthed(needsAdmin ? await api.bootstrap(username.trim(), password) : await api.login(username.trim(), password)); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not reach the BirdFrame API."); setBusy(false); } };
  return <form className="setup-panel auth-panel" onSubmit={submit}><div className="step-title"><span>✦</span><div><p className="eyebrow">{needsAdmin ? "FIRST RUN" : "SIGN IN"}</p><h2>{needsAdmin ? "Create your admin account" : "Welcome back"}</h2></div></div><div className="form-grid"><Field label="Username"><input value={username} autoComplete="username" autoFocus onChange={(e) => setUsername(e.target.value)} /></Field><Field label="Password"><input type="password" value={password} autoComplete="current-password" onChange={(e) => setPassword(e.target.value)} /></Field></div>{error && <p className="form-notice">{error}</p>}<div className="setup-actions"><div></div><button className="button primary" disabled={busy}>{busy ? "Working…" : needsAdmin ? "Create admin account" : "Sign in"}</button></div><p className="help-text">{needsAdmin ? "This is the first account on this BirdFrame — it becomes the administrator and can invite other users." : "Sign in with the account an administrator created for you."}</p></form>;
}

function Setup({ configured, onComplete }: { configured: boolean; onComplete: () => void }) { const [step, setStep] = useState<Step>("location"); const [form, setForm] = useState<Settings>(defaults); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const current = steps.findIndex((s) => s.id === step);
  // The setup guide is also used after first-run. Hydrating it prevents a
  // later visit from presenting defaults that could overwrite saved settings.
  useEffect(() => { void api.settings().then((raw) => setForm(fromApiSettings(raw))).catch(() => undefined); }, []);
  const update = (key: keyof Settings, value: string | boolean) => setForm((old) => ({ ...old, [key]: value }));
  const next = async () => { if (!configured && current < steps.length - 1) { setStep(steps[current + 1].id); return; } setSaving(true); try { await api.saveSettings(toPayload(form)); setNotice(configured ? "Changes saved and applied." : "Your BirdFrame is ready. It will keep watching for visitors."); } catch { setNotice(configured ? "Could not save changes — is the BirdFrame service reachable?" : "Settings are ready to save when the BirdFrame service API is available."); } finally { setSaving(false); } };
  return <div className="setup"><div className="setup-intro"><p className="eyebrow">{configured ? "SETUP" : "FIRST-RUN SETUP"}</p><h2>{configured ? "Tune your BirdFrame." : "Connect BirdFrame to your backyard."}</h2><p>Source, TV, artwork style, asset packs, and display rhythm all live in this guide. Changes are saved when you finish (or with Save on an already-configured frame).</p></div><div className="stepper">{steps.map((item, i) => <button key={item.id} className={item.id === step ? "current" : i < current ? "complete" : ""} onClick={() => setStep(item.id)}><span>{i < current ? "✓" : item.icon}</span>{item.label}</button>)}</div><article className="setup-panel"><div className="step-title"><span>0{current + 1}</span><div><p className="eyebrow">{steps[current].label}</p><h2>{stepTitle(step, form.source)}</h2></div></div>{step === "location" && <LocationForm form={form} update={update} />}{step === "source" && <SourceForm form={form} update={update} />}{step === "tv" && <TvForm form={form} update={update} />}{step === "artwork" && <ArtworkForm form={form} update={update} />}{step === "assets" && <AssetStep form={form} update={update} />}{step === "display" && <DisplayForm form={form} update={update} />}<div className="setup-actions"><button className="button ghost" disabled={current === 0} onClick={() => setStep(steps[current - 1].id)}>← Back</button><div>{notice && <span className="form-notice">{notice}</span>}<button className="button primary" disabled={saving} onClick={() => void next()}>{saving ? "Saving…" : configured ? "Save" : current === steps.length - 1 ? "Finish setup" : "Continue →"}</button></div></div>{notice && !configured && current === steps.length - 1 && <button className="text-button finish" onClick={onComplete}>Go to dashboard →</button>}</article></div> }
function Field({ label, hint, badge, children }: { label: string; hint?: string; badge?: ReactNode; children: ReactNode }) { return <label className="field"><span>{label}{badge}</span>{children}{hint && <small>{hint}</small>}</label> }
function LocationForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <div className="form-grid"><Field label="Place name"><input value={form.label} placeholder="e.g. Oslo, Norway" onChange={(e) => update("label", e.target.value)} /></Field><Field label="Time zone"><input value={form.timezone} onChange={(e) => update("timezone", e.target.value)} /></Field><Field label="Latitude" hint="Stored locally; used to filter likely species."><input value={form.latitude} inputMode="decimal" placeholder="59.9139" onChange={(e) => update("latitude", e.target.value)} /></Field><Field label="Longitude"><input value={form.longitude} inputMode="decimal" placeholder="10.7522" onChange={(e) => update("longitude", e.target.value)} /></Field><div className="privacy-note">⌂ <span><strong>Your location stays with BirdFrame.</strong> It is only shared with an occurrence provider if you choose one for regional artwork.</span></div></div> }
function SourceForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <><div className="choice-row"><button className={form.source === "birdweather-public" ? "choice selected" : "choice"} onClick={() => update("source", "birdweather-public")}><span>☁</span><strong>Public BirdWeather</strong><p>Read a public station by ID. No token or second container needed.</p></button><button className={form.source === "birdweather" ? "choice selected" : "choice"} onClick={() => update("source", "birdweather")}><span>⌁</span><strong>My BirdWeather station</strong><p>Use a private station token you own.</p></button><button className={form.source === "birdnet" ? "choice selected" : "choice"} onClick={() => update("source", "birdnet")}><span>♬</span><strong>Local microphone</strong><p>Connect through the optional BirdNET-Go sidecar.</p></button></div>{form.source === "birdweather-public" ? <Field label="Public station ID" hint="Enter the numeric ID from your station's BirdWeather page; no token is stored."><input type="number" min="1" inputMode="numeric" value={form.birdweatherPublicStationId} placeholder="e.g. 2502" onChange={(e) => update("birdweatherPublicStationId", e.target.value)} /></Field> : form.source === "birdweather" ? <Field label="Station token" hint="Saved encrypted; never shown again after saving."><input type="password" value={form.birdweatherToken} placeholder="Paste your BirdWeather station token" onChange={(e) => update("birdweatherToken", e.target.value)} /></Field> : <Field label="BirdNET-Go address" hint="Start Compose with the local-audio profile first."><input value={form.birdnetUrl} onChange={(e) => update("birdnetUrl", e.target.value)} /></Field>}<p className="help-text">BirdFrame verifies the active source when it starts monitoring. You can revisit this setting at any time.</p></> }
function TvForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <><div className="tv-illustration">▣<span>Samsung<br />The Frame</span></div><div className="form-grid"><Field label="TV name"><input value={form.tvName} placeholder="Living room Frame" onChange={(e) => update("tvName", e.target.value)} /></Field><Field label="IP address"><input value={form.tvIp} placeholder="192.168.1.42" onChange={(e) => update("tvIp", e.target.value)} /></Field></div><p className="help-text">Save this address to pair the TV. Then use “Send current art to TV” from the dashboard and approve the request on the TV.</p></> }
function ArtworkForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) {
  const [packs, setPacks] = useState<Array<{ id: string; illustrations: number; sketches: number }>>([]);
  useEffect(() => { void api.packs().then(setPacks).catch(() => undefined); }, []);
  return <><div className="form-grid"><Field label="Collage style" hint="Original layout uses AvianVisitors' mask-aware, landscape centre-out packing; the field plate adds BirdFrame's border and heading."><select value={form.collageStyle} onChange={(e) => update("collageStyle", e.target.value)}><option value="classic">Classic collage</option><option value="avianvisitors_exact">Avian Visitors — original landscape layout</option><option value="avianvisitors_horizontal">Avian Visitors — horizontal field plate</option></select></Field><Field label="Collage coverage" hint="Coverage applies to Classic and Field plate. Original layout follows AvianVisitors’ species-count density tuning."><select value={form.density} onChange={(e) => update("density", e.target.value)}><option value="sparse">Sparse</option><option value="standard">Balanced</option><option value="full">Full screen</option></select></Field><Field label="Artwork pack" hint="Choose one regional set, or search every installed compatible pack."><select value={form.assetPack} onChange={(e) => update("assetPack", e.target.value)}><option value="all">All installed packs (fallback)</option>{packs.map((pack) => <option key={pack.id} value={pack.id}>{pack.id.replace(/^avianvisitors-/, "")} — {pack.illustrations} illustrations</option>)}</select></Field><Field label="Asset treatment" hint="Use the full-color natural-history illustrations or the upstream pencil sketches."><select value={form.assetVariant} onChange={(e) => update("assetVariant", e.target.value)}><option value="illustrations">Illustrations</option><option value="sketches">Sketches</option></select></Field><Field label="Bird name language" hint="Norwegian uses the NNKF/AviList 2025 database imported from BirdLife Norge."><select value={form.language} onChange={(e) => update("language", e.target.value)}><option value="no">Norwegian (bokmål)</option><option value="en">English detection name</option></select></Field></div><div className="toggle-row"><div><strong>Show Norwegian &amp; Latin bird names</strong><p>Birds are numbered in the artwork and matched to a classical handwritten natural-history legend. Callouts are kept clear of the bird silhouettes.</p></div><button type="button" className={form.labels ? "toggle on" : "toggle"} aria-label="Toggle Norwegian and Latin bird names" onClick={() => update("labels", !form.labels)}><i></i></button></div><Field label="Legend script size" hint="Set the size of the old field-guide script used for Norwegian and scientific names."><select value={form.scriptSize} onChange={(e) => update("scriptSize", e.target.value)}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></Field></>;
}
const LAYOUT_OPTIONS = [
  { id: "collage", label: "Living collage", image: "/layouts/collage.jpg" },
  { id: "latest", label: "Latest visitor", image: "/layouts/latest.jpg" },
  { id: "journal", label: "Field journal", image: "/layouts/journal.jpg" },
];
function LayoutPicker({ value, onChange }: { value: string; onChange: (layout: string) => void }) { return <div className="layout-options">{LAYOUT_OPTIONS.map((option) => <button type="button" key={option.id} className={`layout-option ${value === option.id ? "selected" : ""}`} onClick={() => onChange(option.id)}><img src={option.image} alt={option.label} /><span>{option.label}</span></button>)}</div>; }
function DisplayForm({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) { return <><div className="field layout-field"><span>Display layout</span><LayoutPicker value={form.displayMode} onChange={(v) => update("displayMode", v)} /><small>What the frame shows — click a preview to choose.</small></div><div className="form-grid"><Field label="Collage window"><select value={form.collageWindow} onChange={(e) => update("collageWindow", e.target.value)}><option value="1h">1 hour</option><option value="12h">12 hours</option><option value="24h">24 hours</option><option value="7d">7 days</option></select></Field><Field label="TV updates at most every"><select value={form.refreshMinutes} onChange={(e) => update("refreshMinutes", e.target.value)}><option value="5">5 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option></select></Field></div><div className="form-grid"><Field label="TV MAC address" hint="Needed for automatic wake; for example AA:BB:CC:DD:EE:FF."><input value={form.tvMac} placeholder="AA:BB:CC:DD:EE:FF" onChange={(e) => update("tvMac", e.target.value)} /></Field></div><div className="form-grid"><Field label="Quiet hours start"><input type="time" value={form.quietStart} onChange={(e) => update("quietStart", e.target.value)} /></Field><Field label="Quiet hours end"><input type="time" value={form.quietEnd} onChange={(e) => update("quietEnd", e.target.value)} /></Field></div><div className="toggle-row"><div><strong>Automatically select new artwork on TV</strong><p>Uploads and selects the newest composition at the chosen cadence.</p></div><button type="button" className={form.tvAutoUpdate ? "toggle on" : "toggle"} aria-label="Toggle automatic TV updates" onClick={() => update("tvAutoUpdate", !form.tvAutoUpdate)}><i></i></button></div><div className="toggle-row"><div><strong>Wake TV for a new composition</strong><p>Sends a Wake-on-LAN packet before an automatic update, only outside quiet hours.</p></div><button type="button" className={form.wakeTv ? "toggle on" : "toggle"} aria-label="Toggle wake TV" onClick={() => update("wakeTv", !form.wakeTv)}><i></i></button></div></>; }
function AssetStep({ form, update }: { form: Settings; update: (k: keyof Settings, v: string | boolean) => void }) {
  const [catalog, setCatalog] = useState<Array<{ id: string; version?: string; download_url: string; sha256: string }>>([]);
  const [message, setMessage] = useState("");
  const [installed, setInstalled] = useState<Array<{ id: string; illustrations: number; sketches: number }>>([]);
  const jobs = usePackageJobs();
  const loadCatalog = async () => { try { const current = await api.settings(); await api.saveSettings({ ...current, package_catalog_url: form.catalogUrl }); const items = await api.packageCatalog(); setCatalog(items); setMessage(items.length ? "Catalog URL saved and loaded — install a pack below." : "Catalog URL saved, but the catalog listed no installable packs. Check that entries include id, an HTTPS download_url, and a 64-character sha256."); } catch { setMessage("Could not load catalog. Check that it is a public HTTPS JSON URL."); } };
  const install = async (entry: { id: string; download_url: string }) => { try { const job = await api.installPackageUrl(entry.download_url, entry.id); setMessage(`Install job ${job.id} queued — track it in Activity log.`); } catch { setMessage("Could not queue this package."); } };
  useEffect(() => { void api.packs().then(setInstalled).catch(() => undefined); }, []);
  useEffect(() => { if (jobs.some((job) => job.status === "completed" || job.status === "failed")) void api.packs().then(setInstalled).catch(() => undefined); }, [jobs]);
  return <div><div className="form-grid one"><Field label="Artwork catalog URL" hint="The official catalog is https://avianassets.simenf.com/catalog.json — or any compatible HTTPS catalog."><input value={form.catalogUrl} placeholder="https://avianassets.simenf.com/catalog.json" onChange={(e) => update("catalogUrl", e.target.value)} /></Field></div><div className="button-row"><button type="button" className="button ghost" onClick={() => void loadCatalog()}>Load catalog packages</button></div>{catalog.length > 0 && <div className="package-list">{catalog.map((entry) => <div className="package-entry" key={entry.id}><span><strong>{entry.id}</strong><small>{entry.version || "catalog package"}</small></span><button type="button" className="button small" onClick={() => void install(entry)}>Install</button></div>)}</div>}{message && <p className="form-notice">{message}</p>}<div className="toggle-row"><div><strong>Install activity</strong><p>Installs run in the background — progress and failures appear here and in Activity log.</p></div></div>{jobs.length > 0 ? <div className="package-list">{jobs.map((job) => <PackageJob key={job.id} job={job} />)}</div> : <p className="help-text">No package installs yet.</p>}<div className="toggle-row"><div><strong>Installed packs</strong><p>Packs available to the collage, with illustration and sketch counts.</p></div></div>{installed.length > 0 ? <div className="package-list">{installed.map((pack) => <div className="package-entry" key={pack.id}><span><strong>{pack.id}</strong><small>{pack.illustrations} illustrations · {pack.sketches} sketches</small></span></div>)}</div> : <p className="help-text">No packs installed yet — load the catalog and install one above.</p>}</div>;
}

type Job = { id: number; kind: string; status: string; error?: string; updated_at: string; result?: { phase?: string; progress?: number } };

function usePackageJobs() {
  const [jobs, setJobs] = useState<Job[]>([]);
  useEffect(() => {
    let alive = true;
    const refresh = async () => { try { const all = await api.jobs(); if (alive) setJobs(all.filter((job) => job.kind.startsWith("package"))); } catch { /* service may be starting */ } };
    void refresh();
    const timer = window.setInterval(() => void refresh(), 2000);
    return () => { alive = false; window.clearInterval(timer); };
  }, []);
  return jobs;
}

function PackageJob({ job }: { job: Job }) {
  const active = job.status === "queued" || job.status === "running";
  const pct = job.status === "completed" || job.status === "failed" ? 100 : Math.max(0, Math.min(100, Math.round((job.result?.progress ?? 0) * 100)));
  const label = job.kind === "package_install" ? "Catalog install" : job.kind === "package_upload" ? "Uploaded pack" : "URL install";
  const detail = job.status === "failed" ? job.error || "Install failed" : job.status === "completed" ? "Installed" : job.status === "queued" ? "Queued…" : `${job.result?.phase === "extracting" ? "Extracting" : "Downloading"} ${pct}%`;
  return <div className="package-entry job-entry"><span><strong>{label}</strong><small>{detail}</small></span>{active && <span className="progress-track"><span className="progress-fill" style={{ width: `${Math.max(3, pct)}%` }}></span></span>}</div>;
}
function stepTitle(step: Step, source: string) { return ({ location: "Where do your birds live?", source: source === "birdweather-public" ? "Connect a public BirdWeather station" : source === "birdweather" ? "Connect your BirdWeather station" : "Listen with a local microphone", tv: "Find your Samsung Frame", artwork: "Choose the character of your artwork", assets: "Install artwork packs", display: "Set the rhythm of your display" })[step]; }
function toPayload(s: Settings) { return { location_label: s.label, latitude: s.latitude ? Number(s.latitude) : null, longitude: s.longitude ? Number(s.longitude) : null, timezone: s.timezone, language: s.language, detection_source: s.source === "birdnet" ? "birdnet_go" : s.source === "birdweather-public" ? "birdweather_public" : "birdweather", birdweather_token: s.birdweatherToken || undefined, birdweather_public_station_id: /^\d+$/.test(s.birdweatherPublicStationId) ? Number(s.birdweatherPublicStationId) : null, birdnet_go_url: s.birdnetUrl, tv_host: s.tvIp, tv_mac: s.tvMac, display_mode: s.displayMode === "latest" ? "latest_visitor" : s.displayMode === "journal" ? "journal" : "collage", collage_hours: s.collageWindow === "7d" ? 168 : Number.parseInt(s.collageWindow, 10), tv_auto_update_enabled: s.tvAutoUpdate, tv_wake_enabled: s.wakeTv, tv_quiet_hours_start: s.quietStart, tv_quiet_hours_end: s.quietEnd, tv_update_minutes: Number(s.refreshMinutes), openrouter_api_key: s.openrouterApiKey || undefined, openrouter_model: s.openrouterModel, paper_tone: s.paperTone === "warm cream" ? "#f2e4c9" : s.paperTone === "aged mulberry" ? "#ddc89e" : "#fffaf0", palette: s.palette === "earthy" ? "classic" : s.palette === "muted garden" ? "muted" : "vivid", collage_density: s.density, collage_style: s.collageStyle, labels_enabled: s.labels, legend_script_size: s.scriptSize, package_catalog_url: s.catalogUrl, asset_pack_id: s.assetPack, asset_variant: s.assetVariant }; }
function fromApiSettings(raw: Record<string, unknown>): Settings { return { ...defaults, label: String(raw.location_label || ""), latitude: raw.latitude == null ? "" : String(raw.latitude), longitude: raw.longitude == null ? "" : String(raw.longitude), timezone: String(raw.timezone || defaults.timezone), language: raw.language === "en" ? "en" : "no", source: raw.detection_source === "birdnet_go" ? "birdnet" : raw.detection_source === "birdweather_public" ? "birdweather-public" : "birdweather", birdweatherPublicStationId: raw.birdweather_public_station_id == null ? "" : String(raw.birdweather_public_station_id), birdnetUrl: String(raw.birdnet_go_url || defaults.birdnetUrl), tvIp: String(raw.tv_host || ""), tvMac: String(raw.tv_mac || ""), displayMode: raw.display_mode === "latest_visitor" ? "latest" : raw.display_mode === "journal" ? "journal" : "collage", collageWindow: `${raw.collage_hours || 24}h`.replace("168h", "7d"), tvAutoUpdate: raw.tv_auto_update_enabled !== false, wakeTv: Boolean(raw.tv_wake_enabled), quietStart: String(raw.tv_quiet_hours_start || ""), quietEnd: String(raw.tv_quiet_hours_end || ""), refreshMinutes: String(raw.tv_update_minutes || 5), openrouterModel: String(raw.openrouter_model || ""), paperTone: raw.paper_tone === "#ddc89e" ? "aged mulberry" : raw.paper_tone === "#fffaf0" ? "soft white" : "warm cream", palette: raw.palette === "muted" ? "muted garden" : raw.palette === "vivid" ? "indigo & vermillion" : "earthy", density: String(raw.collage_density || "standard"), collageStyle: raw.collage_style === "avianvisitors_exact" ? "avianvisitors_exact" : raw.collage_style === "avianvisitors_horizontal" ? "avianvisitors_horizontal" : "classic", labels: Boolean(raw.labels_enabled), scriptSize: String(raw.legend_script_size || "medium"), catalogUrl: String(raw.package_catalog_url || ""), assetPack: String(raw.asset_pack_id || "all"), assetVariant: raw.asset_variant === "sketches" ? "sketches" : "illustrations" }; }

function SettingsPanelContent() {
  const [form, setForm] = useState<Settings>(defaults); const [message, setMessage] = useState("");
  const [models, setModels] = useState<Array<{ id: string; name?: string }>>([]); const [operations, setOperations] = useState("");
  const [hasOpenRouterKey, setHasOpenRouterKey] = useState(false);
  const update = (key: keyof Settings, value: string | boolean) => setForm((old) => ({ ...old, [key]: value }));
  useEffect(() => { void api.settings().then((raw) => { setForm(fromApiSettings(raw)); setHasOpenRouterKey(Boolean(raw.has_openrouter_api_key)); }).catch(() => undefined); }, []);
  const save = async (e?: FormEvent) => { e?.preventDefault(); try { await api.saveSettings(toPayload(form)); setMessage("Settings saved. API keys are encrypted at rest."); if (form.openrouterApiKey.trim()) setHasOpenRouterKey(true); return true; } catch { setMessage("Could not save yet. Make sure the BirdFrame API is running."); return false; } };
  const loadModels = async () => { if (!await save()) return; try { setModels(await api.models()); setOperations("Image-capable OpenRouter models loaded."); } catch { setOperations("Could not load models. Check the API key and try again."); } };
  const generate = async () => { if (!await save()) return; try { const species = (await api.occurrences()).filter((entry) => !entry.has_artwork).slice(0, 12).map(({ common_name, scientific_name }) => ({ common_name, scientific_name })); if (!species.length) { setOperations("All observed species already have artwork."); return; } const job = await api.generateArt({ species, poses: "both" }); setOperations(`Artwork job ${job.id} queued for ${species.length} species missing artwork. Track it in Activity log below.`); } catch { setOperations("Could not start artwork generation. Load a model and confirm detections are available."); } };
  return <form className="settings-form" onSubmit={save}>
    <section className="settings-section"><div><p className="eyebrow">OPENROUTER ARTWORK</p><h2>Create your bird library</h2><p>Save your key, load the available image models, choose one, then generate reusable bird assets for the species BirdFrame has observed but still lacks artwork for.</p></div><div><div className="form-grid"><Field label="OpenRouter API key" hint="Encrypted at rest and never returned to the browser after saving." badge={hasOpenRouterKey ? <em className="saved-badge">✓ Key saved</em> : undefined}><input type="password" value={form.openrouterApiKey} placeholder={hasOpenRouterKey ? "sk-or-v1-… (replace only if needed)" : "sk-or-v1-…"} onChange={(e) => update("openrouterApiKey", e.target.value)} /></Field><Field label="Image model"><input list="openrouter-models" value={form.openrouterModel} placeholder="Save key, then load models" onChange={(e) => update("openrouterModel", e.target.value)} /><datalist id="openrouter-models">{models.map((model) => <option key={model.id} value={model.id}>{model.name || model.id}</option>)}</datalist></Field><Field label="Paper tone"><select value={form.paperTone} onChange={(e) => update("paperTone", e.target.value)}><option>warm cream</option><option>aged mulberry</option><option>soft white</option></select></Field><Field label="Palette"><select value={form.palette} onChange={(e) => update("palette", e.target.value)}><option>earthy</option><option>muted garden</option><option>indigo &amp; vermillion</option></select></Field><div className="field layout-field"><span>Display layout</span><LayoutPicker value={form.displayMode} onChange={(v) => update("displayMode", v)} /><small>What the frame shows — click a preview to choose.</small></div></div><div className="setup-actions"><button type="button" className="button ghost" onClick={() => void loadModels()}>Load image models</button><button type="button" className="button primary" onClick={() => void generate()}>Generate artwork for missing species</button></div>{operations && <p className="form-notice">{operations}</p>}<div className="callout"><span>⚠</span><div><strong>Generation costs money</strong><p>Each generation normally costs around 0.06 USD per bird, and only species without artwork are queued.</p></div></div><p className="help-text">Generated PNG assets and compositions are stored under <code>/data/art</code>; Docker Compose maps that directory to <code>./data</code> by default, so they survive image/container updates.</p></div></section>
    <section className="settings-section"><div><p className="eyebrow">DISPLAY API</p><h2>Same art, anywhere</h2><p>The JPEG endpoint serves the byte-identical composition sent to the Frame.</p></div><div className="api-url"><code>{window.location.origin}/api/v1/display/current.jpg</code><a href="/api/v1/display/current.jpg" target="_blank">Open ↗</a></div></section>
    <footer className="save-bar"><span>{message}</span><button className="button primary" type="submit">Save changes</button></footer>
  </form>;
}

function SettingsPanel() { return <SettingsPanelContent />; }

function AccountPage({ user }: { user: { username: string; is_admin: boolean } }) {
  const [keys, setKeys] = useState<ApiKey[]>([]); const [users, setUsers] = useState<User[]>([]);
  const [keyName, setKeyName] = useState(""); const [created, setCreated] = useState<ApiKeyCreated | null>(null);
  const [newUser, setNewUser] = useState({ username: "", password: "", is_admin: false });
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { const [keyList, userList] = await Promise.all([api.listApiKeys(), user.is_admin ? api.listUsers() : Promise.resolve([])]); setKeys(keyList); setUsers(userList); } catch { setMessage("Could not load API keys."); } };
  useEffect(() => { void load(); }, [user.is_admin]);
  const createKey = async () => { if (!keyName.trim()) return; setBusy(true); try { setCreated(await api.createApiKey(keyName.trim())); setKeyName(""); setMessage(""); await load(); } catch { setMessage("Could not create API key."); } finally { setBusy(false); } };
  const revokeKey = async (id: number) => { try { await api.revokeApiKey(id); setCreated(null); await load(); } catch { setMessage("Could not revoke API key."); } };
  const addUser = async () => { if (newUser.username.length < 3 || newUser.password.length < 8) { setMessage("Username needs 3+ characters and password 8+."); return; } setBusy(true); try { await api.createUser(newUser); setNewUser({ username: "", password: "", is_admin: false }); setMessage(""); await load(); } catch (err) { setMessage(err instanceof ApiError ? err.message : "Could not create user."); } finally { setBusy(false); } };
  return <section className="panel settings-form account-page"><section className="settings-section"><div><p className="eyebrow">ACCESS</p><h2>API keys and users</h2><p>Keys authenticate scripts and other clients; the web UI uses a key tied to your login. Signed in as <strong>{user.username}</strong>{user.is_admin ? " (admin)" : ""}.</p></div><div><div className="form-grid"><Field label="New API key name"><input value={keyName} placeholder="e.g. wall display client" onChange={(e) => setKeyName(e.target.value)} /></Field></div><div className="button-row"><button type="button" className="button primary" disabled={busy || !keyName.trim()} onClick={() => void createKey()}>Generate API key</button></div>{created && <div className="api-url"><code>{created.key}</code></div>}{created && <p className="help-text">Copy this key now — it is shown only once. It acts as your account until revoked.</p>}<div className="package-list">{keys.map((key) => <div className="package-entry" key={key.id}><span><strong>{key.name}</strong><small>{key.prefix}… · created {new Date(key.created_at).toLocaleDateString()}{key.last_used_at ? ` · last used ${new Date(key.last_used_at).toLocaleString()}` : " · never used"}</small></span><button type="button" className="button small" onClick={() => void revokeKey(key.id)}>Revoke</button></div>)}</div>{keys.length === 0 && <p className="help-text">No API keys yet — generate one for scripts or other clients.</p>}{user.is_admin && <><div className="toggle-row"><div><strong>Users</strong><p>Additional accounts can sign in to the web UI. Only admins manage users; keys always belong to an account.</p></div></div><div className="form-grid"><Field label="New username"><input value={newUser.username} autoComplete="off" onChange={(e) => setNewUser({ ...newUser, username: e.target.value })} /></Field><Field label="Password (min 8 characters)"><input type="password" value={newUser.password} autoComplete="new-password" onChange={(e) => setNewUser({ ...newUser, password: e.target.value })} /></Field></div><div className="button-row"><button type="button" className="button ghost" disabled={busy} onClick={() => void addUser()}>Create user</button><label className="field field-inline"><input type="checkbox" checked={newUser.is_admin} onChange={(e) => setNewUser({ ...newUser, is_admin: e.target.checked })} /><span>Admin</span></label></div><div className="package-list">{users.map((u) => <div className="package-entry" key={u.id}><span><strong>{u.username}</strong><small>{u.is_admin ? "admin" : "user"} · created {new Date(u.created_at).toLocaleDateString()}</small></span></div>)}</div></>}{message && <p className="form-notice">{message}</p>}</div></section></section>;
}

function LogsPage() {
  const pageSize = 25; const [entries, setEntries] = useState<LogEntry[]>([]); const [offset, setOffset] = useState(0); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false);
  const refresh = async (nextOffset = offset) => { setLoading(true); try { const result = await api.logs(nextOffset, pageSize); setEntries(result.items); setTotal(result.total); setOffset(result.offset); } finally { setLoading(false); } };
  useEffect(() => { void refresh(0); }, []);
  const previous = () => void refresh(Math.max(0, offset - pageSize)); const next = () => void refresh(offset + pageSize);
  const first = total === 0 ? 0 : offset + 1; const last = Math.min(total, offset + entries.length);
  return <section className="panel logs-page"><div className="panel-heading"><div><p className="eyebrow">ACTIVITY LOG</p><h2>What BirdFrame is doing</h2><p className="muted">Source, artwork and display events. Credentials are never written here.</p></div><button type="button" className="button ghost" disabled={loading} onClick={() => void refresh()}>{loading ? "Refreshing…" : "Refresh"}</button></div><div className="detection-list">{entries.length ? entries.map((entry) => <div className="detection" key={entry.id}><div className="bird-thumb">{entry.level === "ERROR" ? "!" : entry.level === "WARNING" ? "!" : "i"}</div><div><strong>{entry.level}</strong><p>{entry.message}</p></div><div className="detection-meta"><span>{new Date(entry.created_at).toLocaleString()}</span></div></div>) : <EmptyState icon="i" title="No events yet" description="Events will appear after saving settings or receiving detections." />}</div><div className="pagination"><span>{total ? `${first}–${last} of ${total}` : "0 events"}</span><div><button type="button" className="button ghost" disabled={loading || offset === 0} onClick={previous}>← Newer</button><button type="button" className="button ghost" disabled={loading || offset + entries.length >= total} onClick={next}>Older →</button></div></div></section>
}
